config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  match '/help', to: 'landing#help', via: 'get'
  match '/about', to: 'landing#about', via: 'get'
  match '/contact', to: 'landing#help', via: 'get'
  match '/news', to: 'landing#news', via: 'get'

  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, presence: true
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 6, maximum: 20}
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  validates :password, length: {minimum: 6}

  before_save {self.email = email.downcase}
  before_create :create_remember_token

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :check_youtube_username

  def check_youtube_username
    if signed_in? && current_user.youtube_username.blank?
      flash.now[:danger] = "Your Youtube username still needs adding to your account!"
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end

  def help
  end

  def contact
  end

  def news
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
      flash[:success] = 'Successfully signed in!'
    else
      flash.now[:danger] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Signed out'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to SubMan!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :name, :email, :youtube_username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "SubMan"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/landing/about.html.haml
- provide(:title, 'About')
%h1 About

app/views/landing/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact

app/views/landing/help.html.haml
- provide(:title, 'Help')
%h1 Help

app/views/landing/index.html.haml
- provide(:title, 'Home')
.center.jumbotron
  %h1 Welcome to SubMan!

  %h2 The third party subscription manager for Youtube

  = link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"

app/views/landing/news.html.haml
- provide(:title, 'News')
%h1 News

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    = link_to image_tag('GitHub-Mark/PNG/GitHub-Mark-32px.png'), 'https://github.com/CuriousCain/SubMan'
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li= link_to "News",    news_path

app/views/layouts/_header.html.haml
%header.navbar-nav.navbar-fixed-top.navbar-inverse
  .container
    .navbar-brand
      = link_to "SubMan", root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Home",    root_path
        %li= link_to "Help",    help_path
        - if signed_in?
          %li.dropdown
            %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown", "data-target" => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", '#'
              %li.divider
              %li= link_to "Sign out", signout_path, method: "delete"
        - else
          %li= link_to "Sign in", signin_path 

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "#{full_title(yield(:title))}"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'

    .container
      - flash.each do |key, value|
        %div{class: "alert alert-#{key}"}
          = value
      = yield
      = render 'layouts/footer'

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      = "#{pluralize(@user.errors.count, 'error')}."
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= "*#{msg}"

app/views/users/edit.html.haml
- provide(:title, "Edit Profile")

%h1 Update your profile

.row
  .col.col-lg-6.col-offset-3
    = form_for @user do |f|
      = render 'shared/error_messages'

      = f.label :youtube_username
      = f.text_field :youtube_username

      %br

      = f.label :password
      = f.password_field :password

      %br

      = f.label :password_confirmation
      = f.password_field :password_confirmation

      %br= f.submit "Save changes", class: "btn btn-lg btn-primary"

app/views/users/index.html.haml
%h1 Listing Users

%table
  %tr
    %th Name
    %th Email

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New User', new_user_path

app/views/users/new.html.haml
- provide(:title, 'Sign Up!')
%h1 New User

.row
  .col.col-lg-6.col-offset-3
    = form_for @user do |u|
      = render 'shared/error_messages'
      
      %br= u.label :username
      = u.text_field :username

      %br= u.label :name
      = u.text_field :name

      %br= u.label :email
      = u.text_field :email

      %br= u.label :password
      = u.password_field :password

      %br= u.label :password_confirmation
      = u.password_field :password_confirmation
      
      %br
      %br
      = u.submit "Create account", class: "btn btn-lg btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.username)

%h1= @user.username

%p= "Name: #{@user.name}"
%p= "Email: #{@user.email}"

- if @user.youtube_username.nil?
  %p= "Youtube Username: "
- else
  %p= "Youtube Username: #{@user.youtube_username}"

%a.btn.btn-lg.btn-primary{:href => edit_user_path(current_user)}
  Edit profile